### ISSUE TITLE
modprobe insert fails

### ISSUE THREAD

**Issue by frank-dspeed** [abperiasamy/rtl8812AU_8821AU_linux#113]
[  498.711274] 8812au: disagrees about version of symbol module_layout
[  525.335027] 8812au: disagrees about version of symbol module_layout

**Comment by btong** [comment]
I saw this with the upgrade from 3.13.0-77-generic to 3.13.0-79-generic

**Comment by harshavardhana** [comment]
> I saw this with the upgrade from 3.13.0-77-generic to 3.13.0-79-generic (ubuntu trusty)

Every kernel upgrade you need to rebuild the module, or add dkms so that dkms does that for you.

**Comment by btong** [comment]
I am using dkms, I have no wifi after the upgrade. Manually running modprobe gives the error above.

**Comment by harshavardhana** [comment]
> I am using dkms, I have no wifi after the upgrade. Manually running modprobe gives the error above.

Some times even with that you have to rebuild, dkms could have failed.
