### ISSUE TITLE
Stuck on boot color splash screen

### ISSUE THREAD

**Issue by khairiAnr** [abperiasamy/rtl8812AU_8821AU_linux#119]
Hi 
Able install the headers and other dependencies part without error 
When i get to this part on my rpi2
Append following at the end of your /boot/config.txt 
kernel=vmlinuz-3.10-3-rpi
initramfs initrd.img-3.10-3-rpi followkernel

after reboot i get stuck on colored splash screen 
after i remove the above on my config.txt, it can boot fine
How do i solve this issue? can someone help me on this

**Comment by babuloseo** [comment]
delete the two lines you added...open up /boot/config.txt and it should work fone.

**Comment by harshavardhana** [comment]
> delete the two lines you added...open up /boot/config.txt and it should work fone.

Closing as per this comment.
