### ISSUE TITLE
RTL8814?

### ISSUE THREAD

**Issue by DanMan** [abperiasamy/rtl8812AU_8821AU_linux#124]
I see mention of that chipset in the sources, but if I plug in a [D-Link DWA-192](https://wikidevi.com/wiki/D-Link_DWA-192), the driver currently doesn't seem to support it, unfortunatly.

Any idea what's missing? The firmware maybe?

**Comment by djpaek** [comment]
unsubscribe  
-----Original Message-----

**Comment by harshavardhana** [comment]
> I see mention of that chipset in the sources, but if I plug in a D-Link DWA-192, the driver currently doesn't seem to support it, unfortunatly.
> 
> Any idea what's missing? The firmware maybe?

Not sure, never really tested it was a community patch.

**Comment by DanMan** [comment]
Well, what would I need to do to test it? I'm about to send it back, so...

**Comment by harshavardhana** [comment]
> Well, what would I need to do to test it? I'm about to send it back, so...

when you say it doesn't support it means that kernel is not able to detect it? are there any messages that you see in 'dmesg' ? 

The problem could be firmware, so validating it would be hard.

**Comment by DanMan** [comment]
Yes. dmesg says the same as without the driver installed. I've tried compiling the other 8812au drivers floating around here on github, to no avail.

**Comment by nicholas5** [comment]
+1 for same problem with TP Link T9U :(

**Comment by ptpt52** [comment]
show your dmesg when plug in the device

**Comment by DanMan** [comment]
https://github.com/diederikdehaas/rtl8814AU
