### ISSUE TITLE
Unable to go to Monitor mode

### ISSUE THREAD

**Issue by syndrid** [abperiasamy/rtl8812AU_8821AU_linux#132]
When I type
`sudo iwconfig wlan1 mode monitor`
I get:
`Error for wireless request "Set Mode" (8B06) :+1: 
SET failed on device wlan ; Invalid argument.`

Other modes work:
`sudo iwconfig wlan1 mode managed`

**Comment by curtiszimmerman** [comment]
If you're looking for monitor mode support that will compile on Ubuntu/LM, [this version](https://github.com/Fredy72/rtl8821au) will get you what you want without updating kernel or gcc as required by other drivers around Github that support monitor mode.

**Comment by ptpt52** [comment]
fixed
