### ISSUE TITLE
module fails to build with kernel higher than 4.7rc..

### ISSUE THREAD

**Issue by oscarbg** [abperiasamy/rtl8812AU_8821AU_linux#133]
using kernels built from ppa for ubuntu..
anyway this works ok with kernel 4.6 or lower..

**Comment by harshavardhana** [comment]
Never tested this on 4.7+ kernel, feel free to send a patch @oscarbg

**Comment by Fjodor42** [comment]
Works for me (I did the PR).

Can someone confirm and close?

**Comment by harshavardhana** [comment]
> Works for me (I did the PR).
> 
> Can someone confirm and close?

Reverted the commit needs a more generic fix here..

**Comment by Fjodor42** [comment]
Agreed, and will do

**Comment by Fjodor42** [comment]
@harshavardhana the one reverted, wasn't that for 4.8-rc? New PR for that coming up shortly...

**Comment by ptpt52** [comment]
Because it is not active
