### ISSUE TITLE
the bug Cause a kernel crash

### ISSUE THREAD

**Issue by okJum** [abperiasamy/rtl8812AU_8821AU_linux#140]
(In STA mode)    when 8812au connected the wifi, then I shut down the wifi signal, the kernel will be print an error, and the kernel will no longer run, unless to restart the system.  (kernel version 3.12.0)

[  245.500000] Path: (null)
[  245.500000] CPU: 0 PID: 370 Comm: RTW_CMD_THREAD Tainted: G           O 3.12.0 #204
[  245.500000] task: 8f0be000 ti: 8f9de000 task.ti: 8f9de000
[  245.500000] 
[ECR   ]: 0x00230400 => Misaligned r/w from 0x7a04acf6
[  245.510000] [EFA   ]: 0x7a04acf6
[  245.510000] [BLINK ]: _issue_probereq+0x116/0x274 [8812au]
[  245.510000] [ERET  ]: _issue_probereq+0x156/0x274 [8812au]
[  245.510000] [STAT32]: 0x00000206 :          E2 E1
[  245.530000] BTA: 0x79f60360   SP: 0x8f9dfeb8  FP: 0x00000000
[  245.530000] LPS: 0x8a24c1b4  LPE: 0x8a24c1c2 LPC: 0x00000000
[  245.540000] r00: 0x8fb76048  r01: 0x00000000 r02: 0x00000018
r03: 0x0000013a r04: 0x00000000 r05: 0x8fb7603f
r06: 0x00000000 r07: 0x00000003 r08: 0x8fecc558
r09: 0x8fecc500 r10: 0x8facb64c r11: 0x00000024
r12: 0x00000093
[  245.540000] 
[  245.540000] Stack Trace:

**Comment by ptpt52** [comment]
just close because it is not active
