### ISSUE TITLE
AWUS036AC does not correspond to the monitor mode?

### ISSUE THREAD

**Issue by RLambert142** [abperiasamy/rtl8812AU_8821AU_linux#145]
I need of help. 
# git clone https://github.com/abperiasamy/rtl8812AU_8821AU_linux

Cloning into 'rtl8812AU_8821AU_linux'...
remote: Counting objects: 843, done.  
remote: Total 843 (delta 0), reused 0 (delta 0), pack-reused 843  
Receiving objects: 100% (843/843), 2.06 MiB | 523.00 KiB/s, done.
Resolving deltas: 100% (432/432), done.
Checking connectivity... done.
# cd ./rtl8812AU_8821AU_linux/
# make

make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/3.16.0-4-amd64/build M=/root/rtl8821au/rtl8812AU_8821AU_linux  modules
make[1]: Entering directory '/usr/src/linux-headers-3.16.0-4-amd64'
Makefile:10: **\* mixed implicit and normal rules: deprecated syntax
make[1]: Entering directory `/usr/src/linux-headers-3.16.0-4-amd64'
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/core/rtw_cmd.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/core/rtw_security.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/core/rtw_debug.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/core/rtw_io.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/core/rtw_ioctl_query.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/core/rtw_ioctl_set.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/core/rtw_ieee80211.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/core/rtw_mlme.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/core/rtw_mlme_ext.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/core/rtw_wlan_util.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/core/rtw_vht.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/core/rtw_pwrctrl.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/core/rtw_rf.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/core/rtw_recv.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/core/rtw_sta_mgt.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/core/rtw_ap.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/core/rtw_xmit.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/core/rtw_p2p.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/core/rtw_tdls.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/core/rtw_br_ext.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/core/rtw_iol.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/core/rtw_sreset.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/core/efuse/rtw_efuse.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/os_dep/osdep_service.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/os_dep/linux/os_intfs.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/os_dep/linux/usb_intf.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/os_dep/linux/usb_ops_linux.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/os_dep/linux/ioctl_linux.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/os_dep/linux/xmit_linux.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/os_dep/linux/mlme_linux.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/os_dep/linux/recv_linux.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/os_dep/linux/ioctl_cfg80211.o
/root/rtl8821au/rtl8812AU_8821AU_linux/os_dep/linux/ioctl_cfg80211.c:5252:2: warning: initialization from incompatible pointer type [enabled by default]
  .change_station = cfg80211_rtw_change_station,
  ^
/root/rtl8821au/rtl8812AU_8821AU_linux/os_dep/linux/ioctl_cfg80211.c:5252:2: warning: (near initialization for ‘rtw_cfg80211_ops.change_station’) [enabled by default]
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/os_dep/linux/rtw_android.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/hal_intf.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/hal_com.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/hal_com_phycfg.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/hal_phy.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/led/hal_usb_led.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/HalPwrSeqCmd.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/rtl8812a/Hal8812PwrSeq.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/rtl8812a/Hal8821APwrSeq.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/rtl8812a/rtl8812a_xmit.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/rtl8812a/rtl8812a_sreset.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/rtl8812a/rtl8812a_hal_init.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/rtl8812a/rtl8812a_phycfg.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/rtl8812a/rtl8812a_rf6052.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/rtl8812a/rtl8812a_dm.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/rtl8812a/rtl8812a_rxdesc.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/rtl8812a/rtl8812a_cmd.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/rtl8812a/usb/usb_halinit.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/rtl8812a/usb/rtl8812au_led.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/rtl8812a/usb/rtl8812au_xmit.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/rtl8812a/usb/rtl8812au_recv.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/rtl8812a/usb/usb_ops_linux.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/rtl8812a/rtl8812a_mp.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/OUTSRC/odm_debug.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/OUTSRC/odm_interface.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/OUTSRC/odm_HWConfig.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/OUTSRC/odm.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/OUTSRC/HalPhyRf.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/OUTSRC/rtl8812a/HalHWImg8812A_FW.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/OUTSRC/rtl8812a/HalHWImg8812A_MAC.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/OUTSRC/rtl8812a/HalHWImg8812A_BB.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/OUTSRC/rtl8812a/HalHWImg8812A_RF.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/OUTSRC/rtl8812a/HalHWImg8812A_TestChip_FW.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/OUTSRC/rtl8812a/HalHWImg8812A_TestChip_MAC.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/OUTSRC/rtl8812a/HalHWImg8812A_TestChip_BB.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/OUTSRC/rtl8812a/HalHWImg8812A_TestChip_RF.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/OUTSRC/rtl8812a/HalPhyRf_8812A.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/OUTSRC/rtl8812a/odm_RegConfig8812A.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/OUTSRC/rtl8821a/HalHWImg8821A_FW.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/OUTSRC/rtl8821a/HalHWImg8821A_MAC.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/OUTSRC/rtl8821a/HalHWImg8821A_BB.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/OUTSRC/rtl8821a/HalHWImg8821A_RF.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/OUTSRC/rtl8821a/HalHWImg8821A_TestChip_MAC.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/OUTSRC/rtl8821a/HalHWImg8821A_TestChip_BB.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/OUTSRC/rtl8821a/HalHWImg8821A_TestChip_RF.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/OUTSRC/rtl8821a/HalPhyRf_8821A.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/hal/OUTSRC/rtl8821a/odm_RegConfig8821A.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/core/rtw_mp.o
  CC [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/core/rtw_mp_ioctl.o
  LD [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/8812au.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /root/rtl8821au/rtl8812AU_8821AU_linux/8812au.mod.o
  LD [M]  /root/rtl8821au/rtl8812AU_8821AU_linux/8812au.ko
make[1]: Leaving directory '/usr/src/linux-headers-3.16.0-4-amd64'
# make install

install -p -m 644 8812au.ko  /lib/modules/3.16.0-4-amd64/kernel/drivers/net/wireless/
/sbin/depmod -a 3.16.0-4-amd64
# iwconfig

eth0      no wireless extensions.

lo        no wireless extensions.

wlan1     unassociated  Nickname:"WIFI@REALTEK"
          Mode:Auto  Frequency=2.412 GHz  Access Point: Not-Associated  
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality:0  Signal level:0  Noise level:0
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
# ifconfig

eth0      Link encap:Ethernet  HWaddr 00:80:00:48:AA:88
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:100
          Interrupt:5 Base address:0x120

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:3924  Metric:1
          RX packets:16 errors:0 dropped:0 overruns:0 frame:0
          TX packets:16 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
# ifconfig wlan1 up
# airmon-ng

PHY     Interface       Driver          Chipset

phy0    wlan1           ??????          Realtek Semiconductor Corp. 
# airmon-ng start wlan1

PHY     Interface       Driver          Chipset

phy0    wlan1           ??????          Realtek Semiconductor Corp. 
cat: /sys/class/ieee80211/phy0/device/net/wlan1mon/type: No such file or directory.

Newly created monitor mode interface wlan1mon is _NOT_ in monitor mode.
Removing non-monitor wlan1mon interface...

WARNING: unable to start monitor mode, please run "airmon-ng check kill"
# airmon-ng check kill
# airmon-ng start wlan1

PHY     Interface       Driver          Chipset

phy0    wlan1           ??????          Realtek Semiconductor Corp. 
cat: /sys/class/ieee80211/phy0/device/net/wlan1mon/type: No such file or directory.

Newly created monitor mode interface wlan1mon is _NOT_ in monitor mode.
Removing non-monitor wlan1mon interface...

WARNING: unable to start monitor mode, please run "airmon-ng check kill"

**Comment by yuri-sevatz** [comment]
Pretty sure this is a problem with all versions of the driver (Including 4.3.22-beta).

The created interface doesn't show up in device/net/*, that's why the airmon-ng script fails.  I'm still learning about the underlying Kernel APIs here, but I'm not 100% sure the driver actually creates nodes in /sys/class/.../$PHY/device/net/* .

However, after executing the iw command that airmon-ng calls to run thsi check, the "iw dev" command seems to disagree with airmon-ng here -- in that the interface is actually defined, and shows up as the right type.

Not sure you'd want to chance running this driver with multiple phy's though 👎 .  Best just use the oldschool "iwconfig <iface> mode monitor".

**Comment by ptpt52** [comment]
fixed
