### ISSUE TITLE
Issues with deadlocks

### ISSUE THREAD

**Issue by paulashford1975** [abperiasamy/rtl8812AU_8821AU_linux#151]
Hi, I sort of have the driver working on linux arm 4.5.2 however when I do an ifconfig up I receive the following;

[  115.902867] =============================================
[  115.908276] [ INFO: possible recursive locking detected ]
[  115.913687] 4.5.4 #1 Tainted: G           O  
[  115.918138] ---------------------------------------------
[  115.923548] ifconfig/416 is trying to acquire lock:
[  115.928435](pmutex){+.+...}, at: [<bf0d6a40>] usbctrl_vendorreq+0x84/0x260 [8812au]
[  115.936489] 
               but task is already holding lock:
[  115.942334](pmutex){+.+...}, at: [<bf0d5574>] netdev_open+0x30/0x58 [8812au]
[  115.949733] 
               other info that might help us debug this:
[  115.956275]  Possible unsafe locking scenario:

[  115.962207]        CPU0
[  115.964656]        ----
[  115.967106]   lock(pmutex);
[  115.969923]   lock(pmutex);
[  115.972741] 
                **\* DEADLOCK ***

[  115.978675]  May be due to missing lock nesting notation

[  115.985478] 2 locks held by ifconfig/416:
[  115.989494]  #0:  (rtnl_mutex){+.+.+.}, at: [<c053dec0>] rtnl_lock+0x1c/0x20
[  115.996614]  #1:  (pmutex){+.+...}, at: [<bf0d5574>] netdev_open+0x30/0x58 [8812au]
[  116.004457] 
               stack backtrace:
[  116.008825] CPU: 1 PID: 416 Comm: ifconfig Tainted: G           O    4.5.4 #1
[  116.015975] Hardware name: Marvell Armada 380/385 (Device Tree)
[  116.021907] Backtrace: 
[  116.024375] [<c00142fc>](dump_backtrace) from [<c00144f8>](show_stack+0x18/0x1c)
[  116.031960]  r6:600c0093 r5:00000000 r4:c08ff920 r3:dc8ba704
[  116.037679] [<c00144e0>](show_stack) from [<c02a2fa8>](dump_stack+0xb8/0xe4)
[  116.044922] [<c02a2ef0>](dump_stack) from [<c0074b10>](__lock_acquire+0x161c/0x2150)
[  116.052856]  r8:00000027 r7:eeb6e220 r6:eeb6e200 r5:00000000 r4:c0a8b6e0 r3:00000002
[  116.060673] [<c00734f4>](__lock_acquire) from [<c0075eec>](lock_acquire+0x78/0x98)
[  116.068432]  r10:bf0d6a40 r9:eeb04f7c r8:00000009 r7:00000001 r6:00000000 r5:600c0013
[  116.076334]  r4:00000000
[  116.078885] [<c0075e74>](lock_acquire) from [<c0687980>](mutex_lock_interruptible_nested+0x64/0x494)
[  116.088210]  r7:eeb6e200 r6:c1134674 r5:eeb04800 r4:00000000
[  116.094041] [<c068791c>](mutex_lock_interruptible_nested) from [<bf0d6a40>](usbctrl_vendorreq+0x84/0x260 [8812au])
[  116.104587]  r10:00000001 r9:00000001 r8:00000009 r7:edef3c00 r6:eeb04800 r5:eeb04800
[  116.112487]  r4:eeb04800
[  116.115258] [<bf0d69bc>](usbctrl_vendorreq [8812au]) from [<bf0f8a34>](usb_read8+0x38/0x44 [8812au])
[  116.124584]  r10:00000000 r9:0001b180 r8:00000000 r7:f10aa000 r6:eeb04800 r5:eeb04800
[  116.132484]  r4:f10a4000
[  116.135244] [<bf0f89fc>](usb_read8 [8812au]) from [<bf09fea8>](_rtw_read8+0x20/0x24 [8812au])
[  116.144175] [<bf09fe88>](_rtw_read8 [8812au]) from [<bf10d280>](rtl8812au_hal_init+0x40/0x10a8 [8812au])
[  116.154074] [<bf10d240>](rtl8812au_hal_init [8812au]) from [<bf0e807c>](rtw_hal_init+0x20/0x120 [8812au])
[  116.163837]  r10:00000000 r9:0001b180 r8:00000000 r7:eeb07830 r6:f10a4000 r5:eeb04800
[  116.171738]  r4:eeb04800
[  116.174506] [<bf0e805c>](rtw_hal_init [8812au]) from [<bf0d5458>](_netdev_open+0x6c/0x158 [8812au])
[  116.183746]  r8:00000000 r7:eeb07830 r6:eeb07800 r5:eeb04800 r4:f10a4000 r3:f10a8000
[  116.191779] [<bf0d53ec>](_netdev_open [8812au]) from [<bf0d557c>](netdev_open+0x38/0x58 [8812au])
[  116.200845]  r6:bf16e474 r5:f10a4000 r4:eeb07800 r3:00000001
[  116.206671] [<bf0d5544>](netdev_open [8812au]) from [<c052e9f4>](__dev_open+0xb0/0x114)
[  116.214866]  r5:00000001 r4:eeb07800
[  116.218472] [<c052e944>](__dev_open) from [<c052ecb0>](__dev_change_flags+0x9c/0x14c)
[  116.226492]  r7:00001002 r6:00001043 r5:00000001 r4:eeb07800
[  116.232209] [<c052ec14>](__dev_change_flags) from [<c052ed80>](dev_change_flags+0x20/0x50)
[  116.240664]  r8:00000000 r7:be86aa60 r6:00001002 r5:eeb07944 r4:eeb07800 r3:00000000
[  116.248483] [<c052ed60>](dev_change_flags) from [<c05acae4>](devinet_ioctl+0x754/0x83c)
[  116.256677]  r8:00000000 r7:be86aa60 r6:c08e74c8 r5:eeaa140c r4:ed097e7c r3:00000000
[  116.264494] [<c05ac390>](devinet_ioctl) from [<c05aebd0>](inet_ioctl+0x1a8/0x1d0)
[  116.272166]  r10:00000000 r9:ed096000 r8:00000004 r7:eefa9d40 r6:be86aa60 r5:eefa9d60
[  116.280067]  r4:00008914
[  116.282618] [<c05aea28>](inet_ioctl) from [<c050db7c>](sock_ioctl+0x244/0x320)
[  116.290034] [<c050d938>](sock_ioctl) from [<c01379ac>](do_vfs_ioctl+0xa8/0x9b4)
[  116.297532]  r7:c01382f4 r6:eeb21a00 r5:eefa9d60 r4:be86aa60
[  116.303248] [<c0137904>](do_vfs_ioctl) from [<c01382f4>](SyS_ioctl+0x3c/0x64)
[  116.310571]  r10:00000000 r9:ed096000 r8:00000004 r7:00008914 r6:eeb21a00 r5:be86aa60
[  116.318472]  r4:eeb21a00
[  116.321023] [<c01382b8>](SyS_ioctl) from [<c000fd20>](ret_fast_syscall+0x0/0x1c)
[  116.328609]  r8:c000fec4 r7:00000036 r6:00000041 r5:be86aac8 r4:0002cdd0 r3:00001043
[  116.561586] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[  118.562952] RTL871X: nolinked power save enter

I have also found that I cannot get wlan0 to auto up on boot, thanks in advance.

**Comment by ptpt52** [comment]
not about the current code
