### ISSUE TITLE
Doesn't compile with dkms on Ubuntu 16.10

### ISSUE THREAD

**Issue by Grief** [abperiasamy/rtl8812AU_8821AU_linux#167]
`sudo make -f Makefile.dkms install`
ends with
`make: *** No targets.  Stop`

**Comment by Grief** [comment]
`git revert f5f3cfa492428e6bedd86912669ac02601738368` helped to compile the module. What the hell that commit supposed to achieve??

**Comment by Grief** [comment]
However, the driver doesn't work. Sometimes it just says `wlan0 link is not ready`, sometimes there are a few networks found but connections to any of them fail.

**Comment by ptpt52** [comment]
the latest HEAD fixed, thanks for reporting this bug.
