### ISSUE TITLE
Install driver fro tp-link T4UH in Arch setup

### ISSUE THREAD

**Issue by ol3gart** [abperiasamy/rtl8812AU_8821AU_linux#170]
Hello!
I try to install a new Arch system on my PC, but i have a trouble - i dont have a wired connection to inet, only wifi.
How can i install this driver in my system?

**Comment by sciencefyll** [comment]
connect your android phone and enable usb tethering. then do a dhcpcd "ip link id".

"ip link id" is the id of you newly connected android device over usb.
