### ISSUE TITLE
TP-LINK T4UH not working, changing driver from *21 to *12 fixed it

### ISSUE THREAD

**Issue by andersfylling** [abperiasamy/rtl8812AU_8821AU_linux#175]
I tried compiling this and everything worked except, the wifi.

After going into the [usb_intf.c file](https://github.com/abperiasamy/rtl8812AU_8821AU_linux/blob/master/os_dep/linux/usb_intf.c) and changed line 315 from "...RTL8821..." to "...RTL8812...":
`{USB_DEVICE(0x2357, 0x0103),.driver_info = RTL8821}, /* TP-Link - T4UH */`

to

`{USB_DEVICE(0x2357, 0x0103),.driver_info = RTL8812}, /* TP-Link - T4UH */`

My wifi dongle now works 0.o

**Comment by ptpt52** [comment]
ok, retry the repo HEAD

**Comment by raphting** [comment]
This change seems to be upstream, so I suggest closing this issue.
