### ISSUE TITLE
Why is commits by ptpt52 being allowed?

### ISSUE THREAD

**Issue by lepoopyliker** [abperiasamy/rtl8812AU_8821AU_linux#185]
Has anyone seen his commits? Literally spammed hundreds of thousands of lines of code by simply removing and adding additional, unnecessary code into this repo. I went through several components today, but there is literally so much there is no way of telling if something malicious or dangerous slipped into here. All of his commits should be reversed IMO

**Comment by ptpt52** [comment]
and cleanup all compile warnning and something is bug fix

**Comment by lepoopyliker** [comment]
Ok I was just checking. I did not mean to come off in a bad way, I was just concerned. Thanks for doing all that. :).
