### ISSUE TITLE
Kernel Ooops: BUG: unable to handle kernel NULL pointer dereference

### ISSUE THREAD

**Issue by reavertm** [abperiasamy/rtl8812AU_8821AU_linux#201]
Disclaimer: this might be some subtlety caused by router as I don't recall those any issues when using previous one. Those happened to appear relatively recently and I cannot pinpoint what caused this.

Router: UPC Connect Box (5GHz and 2,4GHz, auto-channel assignment, WPA2)
Device: TP-Link Archer 4TU USB
Reproducible: always

Latest git version of this rtl8812 driver crashes, relevant part of dmesg:

[   22.852517] RTL871X: rtw_set_802_11_connect(wlan0)  fw_state=0x00000008
[   30.228731] RTL871X: rtw_set_802_11_connect(wlan0)  fw_state=0x00000008
[   30.594112] RTL871X: start auth
[   30.596595] RTL871X: auth success, start assoc
[   30.610250] RTL871X: rtw_cfg80211_indicate_connect(wlan0) BSS not found !!
[   30.610260] RTL871X: assoc success
[   30.610281] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   30.717995] RTL871X: send eapol packet
[   30.724581] RTL871X: send eapol packet
[   30.724646] RTL871X: set pairwise key camid:4, addr:54:67:51:cc:4d:00, kid:0, type:AES
[   30.733754] RTL871X: set group key camid:5, addr:54:67:51:cc:4d:00, kid:1, type:AES
[   56.672893] RTL871X: rtw_set_802_11_connect(wlan0)  fw_state=0x00000009
[   56.680301] BUG: unable to handle kernel paging request at ffffc9000d346001
[   56.680303] IP: [<ffffffffa18eadb6>] join_cmd_hdl+0x148/0x311 [rtl8812au]
[   56.680319] PGD 21580d067 
[   56.680319] PUD 21580e067 
[   56.680320] PMD 20b9b4067 
[   56.680321] PTE 0

[   56.680322] Oops: 0000 [#1] PREEMPT SMP
[   56.680323] Modules linked in: nvidia_modeset(PO) rtl8812au(O) nvidia(PO) nvidia_drm(PO) vboxpci(O) vboxnetadp(O) vboxnetflt(O) zram vboxdrv(O)
[   56.680329] CPU: 1 PID: 4656 Comm: RTW_CMD_THREAD Tainted: P           O    4.9.6-gentoo-r1 #1
[   56.680329] Hardware name: System manufacturer System Product Name/P8P67 DELUXE, BIOS 3602 10/31/2012
[   56.680330] task: ffff8802139b55c0 task.stack: ffffc90000350000
[   56.680331] RIP: 0010:[<ffffffffa18eadb6>]  [<ffffffffa18eadb6>] join_cmd_hdl+0x148/0x311 [rtl8812au]
[   56.680341] RSP: 0018:ffffc90000353e48  EFLAGS: 00010297
[   56.680341] RAX: ffffc9000d345ff5 RBX: ffffc9000d340000 RCX: 0000000000000000
[   56.680342] RDX: 0000000000000002 RSI: ffffc9000d34128a RDI: ffffc9000d34119c
[   56.680343] RBP: 0000000000004db3 R08: 00000000ffffffd3 R09: 000000000000002d
[   56.680343] R10: ffffea000856f400 R11: ffff880215803a00 R12: ffffc9000d346001
[   56.680344] R13: ffffc9000d3411d2 R14: 0000000000000001 R15: ffff8802139b55c0
[   56.680345] FS:  0000000000000000(0000) GS:ffff88021ec40000(0000) knlGS:0000000000000000
[   56.680346] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   56.680347] CR2: ffffc9000d346001 CR3: 0000000001c07000 CR4: 00000000000406e0
[   56.680347] Stack:
[   56.680348]  0000000000000297 ffff880215bd2ba0 ffffc9000d340000 ffffc9000d341b58
[   56.680349]  ffffc9000d341b28 00000000fffc4900 ffffffffa18cb8ea ffffc9000d341b68
[   56.680351]  ffff880208116200 ffffc9000d341ba4 ffffc9000d341b40 ffff8802139b55c0
[   56.680352] Call Trace:
[   56.680359]  [<ffffffffa18cb8ea>] ? rtw_cmd_thread+0x27a/0x390 [rtl8812au]
[   56.680365]  [<ffffffffa18cb670>] ? rtw_stop_cmd_thread+0x49/0x49 [rtl8812au]
[   56.680368]  [<ffffffff8105e459>] ? kthread+0xb9/0xd0
[   56.680370]  [<ffffffff8105e3a0>] ? kthread_park+0x50/0x50
[   56.680372]  [<ffffffff81708c92>] ? ret_from_fork+0x22/0x30
[   56.680373] Code: 89 e7 e8 99 0c 00 00 66 89 83 6a 11 00 00 41 be 00 00 00 00 bd 0c 00 00 00 4c 8d ab d2 11 00 00 89 e8 49 8d 44 05 70 4c 8d 60 0c <0f> b6 40 0c 3c bf 0f 84 dd 00 00 00 3c bf 77 0d 3c 2d 74 47 3c 
[   56.680390] RIP  [<ffffffffa18eadb6>] join_cmd_hdl+0x148/0x311 [rtl8812au]
[   56.680399]  RSP <ffffc90000353e48>
[   56.680399] CR2: ffffc9000d346001
[   56.680400] ---[ end trace 34ae5c672a482f1f ]---
[   56.680403] BUG: unable to handle kernel NULL pointer dereference at           (null)
[   56.680405] IP: [<ffffffff81076fa3>] __wake_up_common+0x23/0x80
[   56.680407] PGD 0 

[   56.680408] Oops: 0000 [#2] PREEMPT SMP
[   56.680408] Modules linked in: nvidia_modeset(PO) rtl8812au(O) nvidia(PO) nvidia_drm(PO) vboxpci(O) vboxnetadp(O) vboxnetflt(O) zram vboxdrv(O)
[   56.680412] CPU: 1 PID: 4656 Comm: RTW_CMD_THREAD Tainted: P      D    O    4.9.6-gentoo-r1 #1
[   56.680413] Hardware name: System manufacturer System Product Name/P8P67 DELUXE, BIOS 3602 10/31/2012
[   56.680414] task: ffff8802139b55c0 task.stack: ffffc90000350000
[   56.680414] RIP: 0010:[<ffffffff81076fa3>]  [<ffffffff81076fa3>] __wake_up_common+0x23/0x80
[   56.680416] RSP: 0018:ffffc90000353e78  EFLAGS: 00010096
[   56.680416] RAX: 0000000000000286 RBX: ffffc90000353f20 RCX: 0000000000000000
[   56.680417] RDX: 0000000000000000 RSI: 0000000000000003 RDI: ffffc90000353f20
[   56.680418] RBP: ffffc90000353f28 R08: 0000000000000000 R09: 0000000000000000
[   56.680418] R10: 0000000000000000 R11: 0000000000000361 R12: 0000000000000000
[   56.680419] R13: 0000000000000000 R14: 0000000000000003 R15: 0000000000030001
[   56.680420] FS:  0000000000000000(0000) GS:ffff88021ec40000(0000) knlGS:0000000000000000
[   56.680421] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   56.680421] CR2: 0000000000000000 CR3: 0000000001c07000 CR4: 00000000000406e0
[   56.680422] Stack:
[   56.680422]  0000000100000046 ffffc90000353f20 ffffc90000353f18 0000000000000286
[   56.680424]  0000000000000000 0000000000000046 0000000000030001 ffffffff810778fc
[   56.680425]  ffff8802139b5be0 ffff8802139b55c0 0000000000000000 ffffffff81042ed1
[   56.680427] Call Trace:
[   56.680428]  [<ffffffff810778fc>] ? complete+0x2c/0x40
[   56.680430]  [<ffffffff81042ed1>] ? mm_release+0xa1/0x120
[   56.680431]  [<ffffffff81046c3c>] ? do_exit+0x12c/0xa80
[   56.680433]  [<ffffffff8170a3a7>] ? rewind_stack_do_exit+0x17/0x20
[   56.680433] Code: 0f 1f 84 00 00 00 00 00 41 57 41 56 41 89 f6 41 55 41 89 cd 41 54 4d 89 c4 55 48 8d 6f 08 53 48 83 ec 08 89 54 24 04 48 8b 57 08 <48> 8b 32 48 8d 42 e8 48 39 d5 4c 8d 7e e8 75 05 eb 38 49 89 d7 
[   56.680451] RIP  [<ffffffff81076fa3>] __wake_up_common+0x23/0x80
[   56.680452]  RSP <ffffc90000353e78>
[   56.680452] CR2: 0000000000000000
[   56.680453] ---[ end trace 34ae5c672a482f20 ]---
[   56.680454] Fixing recursive fault but reboot is needed!
[   56.680455] BUG: scheduling while atomic: RTW_CMD_THREAD/4656/0x00000003
[   56.680455] Modules linked in: nvidia_modeset(PO) rtl8812au(O) nvidia(PO) nvidia_drm(PO) vboxpci(O) vboxnetadp(O) vboxnetflt(O) zram vboxdrv(O)
[   56.680459] CPU: 1 PID: 4656 Comm: RTW_CMD_THREAD Tainted: P      D    O    4.9.6-gentoo-r1 #1
[   56.680459] Hardware name: System manufacturer System Product Name/P8P67 DELUXE, BIOS 3602 10/31/2012
[   56.680460]  0000000000000000 ffffffff812eb51d 0000000000016380 ffffc90000353ed0
[   56.680462]  ffffffff81062458 ffffffff8170484e ffffc90000353ea8 ffff8802139b55c0
[   56.680463]  0000000000000000 0000000000000000 0000000000000046 0000000000030001
[   56.680464] Call Trace:
[   56.680466]  [<ffffffff812eb51d>] ? dump_stack+0x46/0x59
[   56.680468]  [<ffffffff81062458>] ? __schedule_bug+0x48/0x70
[   56.680470]  [<ffffffff8170484e>] ? __schedule+0x27e/0x4f0
[   56.680472]  [<ffffffff81704af4>] ? schedule+0x34/0x80
[   56.680473]  [<ffffffff8104736d>] ? do_exit+0x85d/0xa80
[   56.680474]  [<ffffffff8170a3a7>] ? rewind_stack_do_exit+0x17/0x20
[   71.786129] RTL871X: rtw_set_802_11_connect(wlan0)  fw_state=0x00000008

Previous versions (like f886c92b3aeb6027b8f8ae2f1535dbe65f5d23dd) do not crash, but deathenticate so often that driver is basically useless.

USB power management for Wifi is disabled.

I can rebuild kernel with more verbose output from mac/cfg8011n layer. Git master version crashes on kernel-4.9.6 as well as on older ones (like 4.4.39) I tested.

**Comment by c-andy-martin** [comment]
I too encountered this issue and believe I found the bug and have submitted this pull request:

https://github.com/abperiasamy/rtl8812AU_8821AU_linux/pull/204
