### ISSUE TITLE
dosen't compile after upgrade from  kernel 4.8 to 4.9 debian

### ISSUE THREAD

**Issue by NickNgHK** [abperiasamy/rtl8812AU_8821AU_linux#202]
make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.9.0-0.bpo.2-amd64/build M=/home/xxx/yyy/rtl8812AU_8821AU_linux  modules
make[1]: Entering directory '/lib/modules/4.9.0-0.bpo.2-amd64/build'
make[1]: *** No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/lib/modules/4.9.0-0.bpo.2-amd64/build'
Makefile:1570: recipe for target 'modules' failed
make: *** [modules] Error 2

**Comment by ptpt52** [comment]
install the kernel headers

**Comment by NickNgHK** [comment]
I did. 
sudo apt-get install linux-header-4.9xxx-amd64.
But no difference

**Comment by ptpt52** [comment]
not a problem
