### ISSUE TITLE
performance issues with TRENDnet TEW-805UB on RPI3

### ISSUE THREAD

**Issue by dschwartz783** [abperiasamy/rtl8812AU_8821AU_linux#214]
Basically what the header says. It seems that the adapter is being limited to a single stream of 802.11ac. The adapter supports two-stream and the access point support three-stream 802.11ac (1.3Gbps, AirPort Extreme), and one version of this driver on GitHub (although I'm not sure which) was also able to support the faster speeds, but unfortunately limited me to non-DFS channels, and so I had to switch to this one. It would be nice if we could work out the issue here... Thanks.

**Comment by ptpt52** [comment]
really don't know how to fix this. Any example code?

**Comment by dschwartz783** [comment]
I'm really not certain, but I believe it was the code from this repo that allowed multiple streams: https://github.com/gnab/rtl8812au

Where is the stream count controlled in the driver? I'm fairly new to this codebase.

**Comment by dschwartz783** [comment]
I got it working my manually replacing RF_1T1R with RF_2T2R at https://github.com/abperiasamy/rtl8812AU_8821AU_linux/blob/00aedbde5cb6388ff5abf433d6798370c6a74102/hal/rtl8812a/rtl8812a_hal_init.c#L2192
Which tells me that it must be detecting the number of available antennas incorrectly.

**Comment by dschwartz783** [comment]
Think I was mistaken, never mind.
