### ISSUE TITLE
8812au: disagrees about version of symbol module_layout

### ISSUE THREAD

**Issue by brainstorm** [abperiasamy/rtl8812AU_8821AU_linux#23]
I'm getting the following error message when trying to load the module for this edimax adapter:

https://wikidevi.com/wiki/Edimax_EW-7822UAC

Compiling inside a Raspberry Pi (no cross-compiling).

```
root@rpi:/usr/src/rtl8812AU-git# modprobe 8812au
ERROR: could not insert '8812au': Exec format error
```

In dmesg:

```
[ 2593.836183] 8812au: disagrees about version of symbol module_layout
[ 2616.580796] 8812au: disagrees about version of symbol module_layout
```

I've followed the following blog post:

https://www.debinux.de/2014/06/sitecom-wifi-usb-adapter-ac1200-treiber-dkms-einrichtung-unter-ubuntu/

But I had to do a:

```
# ln -sf /usr/src/linux-headers-3.12-1-rpi /lib/modules/3.12.22+/build
```

Which I guess it's the root of the problem, but since the exact `linux-headers` for my running kernel version (3.12.22+) are not available, I thought that 3.12.x `linux-headers` would be enough.

Any pointers on how can I circumvent this issue?

**Comment by joseph-jja** [comment]
http://stackoverflow.com/questions/20167411/how-to-compile-a-kernel-module-for-raspberry-pi

In case you are still looking.  I found this which talk about compiling modules on pi

**Comment by okazymyrov** [comment]
I have got the same error on Ubuntu 14.04.2 LTS
```
[ 288.292851] 8812au: disagrees about version of symbol module_layout
```

**Comment by joseph-jja** [comment]
Ubuntu on Raspberry pi?

**Comment by okazymyrov** [comment]
Hi @joseph-jja,

Ubuntu war installed on a common PC, but the error is the same. That error appeared when the kernel was updated. The only way I found to fix this is to rebuild rtl8812AU_8821AU_linux
```
    MODULE="rtl8812AU_8821AU_linux"
    MODULE_VERSION="1.0"
    MODULE_SRC_PATH="/usr/src/"

    dkms remove "${MODULE}/${MODULE_VERSION}" --all
    dkms add "${MODULE}/${MODULE_VERSION}"
    dkms build "${MODULE}/${MODULE_VERSION}"
    dkms install --force "${MODULE}/${MODULE_VERSION}"
```

Do you any idea how to fix it without rebuilding?

**Comment by joseph-jja** [comment]
You must rebuild with each kernel update.  No way around that.  You can setup dkms to have that done automatically.  I do it manually music though.

**Comment by philastrophist** [comment]
I've run your script above and it fixed my problem. Thanks a lot! Is there a way to automatically do this when the kernel is updated?

**Comment by joseph-jja** [comment]
Use dkms to do or on every kernel update.  I just do it manually

**Comment by harshavardhana** [comment]
Adding module to dkms will make it automatic for kernel update or manual is another choice. Closing this issue.

**Comment by Id2ndR** [comment]
This bug is the same that https://github.com/diederikdehaas/rtl8812AU/issues/72
