### ISSUE TITLE
Sent eapol packet every 10 min

### ISSUE THREAD

**Issue by ngodber** [abperiasamy/rtl8812AU_8821AU_linux#233]
Hi,

First of all, thanks for the work on keeping this driver working in 4.x kernels. I've compiled against version 4.3.14 succesfully and the dongle is working. I am getting the following however, 

![image](https://user-images.githubusercontent.com/11834846/30460882-4a95c408-99fd-11e7-9326-366f078596e0.png)

I believe this is an issue with the driver as the rpi3 internal wireless doesn't exhibit this issue. Thoughts?

Neil

**Comment by KjellMorgenstern** [comment]
I see those messages, often with 10 minute distance, but  on an ubuntu 16.04 on amd64. 
I have two devices configured in network manager, but only one of the devices (usb dongles) is connected. Still, for both the devices, those messages seem to be triggered.

```
Feb 05 11:50:02 baltar-ubuntu wpa_supplicant[1197]: wlx24050fdbce57: WPA: Group rekeying completed with 38:10:d5:72:85:9b [GTK=CCMP]
Feb 05 11:50:02 baltar-ubuntu kernel: RTL871X: send eapol packet
Feb 05 11:50:02 baltar-ubuntu kernel: RTL871X: set group key camid:6, addr:38:10:d5:72:85:9b, kid:1, type:AES
Feb 05 11:50:02 baltar-ubuntu wpa_supplicant[1197]: wlx000f0045b6f4: WPA: Group rekeying completed with 38:10:d5:72:85:9b [GTK=CCMP]
Feb 05 11:50:02 baltar-ubuntu kernel: RTL871X: send eapol packet
Feb 05 11:50:02 baltar-ubuntu kernel: RTL871X: set group key camid:6, addr:38:10:d5:72:85:9b, kid:1, type:AES
```
Kernel is
Linux version 4.13.0-31-generic (buildd@lcy01-amd64-013) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5))
