### ISSUE TITLE
How to install this driver

### ISSUE THREAD

**Issue by rohitNSA** [abperiasamy/rtl8812AU_8821AU_linux#25]
i did `make` and the `make install` 
when i run `runwpa` it says failed to open wpa1.conf : no such file

**Comment by bits3rpent** [comment]
runwpa file makes a lot of assumptions. The driver _should_ just work  when doing make install. For me my wpa configuration file is in /etc/wpa_supplicant/wpa_supplicant.conf.

**Comment by harshavardhana** [comment]
https://github.com/abperiasamy/rtl8812AU_8821AU_linux/#autocompiling-with-dkms - this should help you install the driver..
