### ISSUE TITLE
Getting an error while using make Kernel: 3.10.0-514.el7.x86_64

### ISSUE THREAD

**Issue by shreymohan94** [abperiasamy/rtl8812AU_8821AU_linux#264]
/root/Downloads/rtl8812AU_8821AU_linux-master/os_dep/linux/os_intfs.c:809:2: error: initialization from incompatible pointer type [-Werror]
  .ndo_select_queue = rtw_select_queue,
  ^
/root/Downloads/rtl8812AU_8821AU_linux-master/os_dep/linux/os_intfs.c:809:2: error: (near initialization for ‘rtw_netdev_ops.<anonymous>.ndo_select_queue’) [-Werror]
cc1: all warnings being treated as errors

**Comment by BeyondPerception** [comment]
I am getting the same error on kernal 3.13.0-32 i386 Ubuntu 12.04. No clue on how to fix

**Comment by harshavardhana** [comment]
Old kernels are not supported..
