### ISSUE TITLE
Is this repository in dead state?

### ISSUE THREAD

**Issue by Mannshoch** [abperiasamy/rtl8812AU_8821AU_linux#346]
Is this repository in dead state?

**Comment by Raspberry1111** [comment]
I think so.

If you need an alternative i have found [this](https://github.com/morrownr/8812au) that seems to work pretty well (for me atleast)

**Comment by Mannshoch** [comment]
Thanks a lot.
Meanwhile, I exchanged the Adapter. Now I have Internet. May check this later again if I switch them back.
