### ISSUE TITLE
Patch b22cbdf breaks WPA2 passphrase authentication

### ISSUE THREAD

**Issue by zebulon2** [abperiasamy/rtl8812AU_8821AU_linux#4]
b22cbdf3b9df225b66d1500ac6bfc4b819d16bbc patch breaks authentication validation on my machine, using WPA2 passphrase. Up to f1008f6 the driver works fine. I use an Edimax AC1200 USB adapter and a Netgear R7000 router under dd-wrt. What info do you need to diagnose the problem? Thanks.

**Comment by bits3rpent** [comment]
Can any of you test this again to make sure the problem still exists?

**Comment by Umookaep** [comment]
I had this problem with Debian wheezy 3.2. kernel. Connection to the AP worked without enryption but with WPA2 not. Now it switched to 3.16. kernel and it works with 2.4 GHz

**Comment by bits3rpent** [comment]
Let's move this to my repo since this one is inactive. I will get on it. https://github.com/bits3rpent/rtl8812AU_8821AU_linux

**Comment by harshavardhana** [comment]
Should be working with latest merge, thanks to @bits3rpent

**Comment by bits3rpent** [comment]
:+1:  Glad to see activity again!
