### ISSUE TITLE
Compile warning in ioctl_linux.c:8887:67: warning: iteration 16u invokes undefined behavior

### ISSUE THREAD

**Issue by AndyPi** [abperiasamy/rtl8812AU_8821AU_linux#61]
I compiled the driver on arch linux raspberry pi.  It compiles but issues various warning messages.  It seems to work well, even at 5G connecting to my router at 434Mbps and achieving bandwidth (measured by iperf of > 200Mbps).  The later version I received from Edimax rtl8811AU_linux_v4.3.7_11618.20141029 doesnt work at 5G and isnt set to use CFG80211 and doesnt even compile if it is switched on.  So I decided to go with your (and others) work, which seems to be active.

The first compile warning is 
os_dep/linux/ioctl_linux.c: In function ‘rtw_mp_efuse_get’:
os_dep/linux/ioctl_linux.c:8887:67: warning: iteration 16u invokes undefined behavior [-Waggressive-loop-optimizations]
     sprintf(extra, "%s%02X ", extra, (pEfuseHal->fakeEfuseInitMap)[i+j]);
 os_dep/linux/ioctl_linux.c:8875:3: note: containing loop
   for (i = 0; i < EFUSE_MAP_SIZE; i += 16)
 
Because EFUSE_MAP_SIZE = 512 and array limit is EFUSE_MAX_MAP_LEN = 256 this looked wrong! 
 
Array fakeEfuseInitMap[] has EFUSE_MAX_MAP_LEN elements.  This is set in include/rtw_efuse.h.  In your version v4.2.2_7502.20130517 this is set to 256 but in v4.3.7_11618.20141029 its set to 512

Changing removes warning message.

I am new to GIT and want to contribute and have created a pull request.  Hope you can accept it, others will follow.

regards

Andy

**Comment by harshavardhana** [comment]
Fixed by #62
