### ISSUE TITLE
Stacke trace on kernel 3.13 wheb unplugging wifi dongle

### ISSUE THREAD

**Issue by nbenm** [abperiasamy/rtl8812AU_8821AU_linux#7]
Hi,

I'm using kernel 3.13. When I unplug my wifi dongle a stack trace is produced.
Here it is

[ 4247.778321] ------------[ cut here ]------------
[ 4247.778346] WARNING: CPU: 0 PID: 81 at /build/linux-ncyRvS/linux-3.13.5/net/wireless/core.c:961 cfg80211_netdev_notifier_call+0x2bf/0x5a0 [cfg80211]()
[ 4247.778351] Modules linked in: usb_storage 8812au(O) cfg80211 pci_stub vboxpci(O) vboxnetadp(O) vboxnetflt(O) snd_hrtimer cpufreq_powersave cpufreq_userspace cpufreq_stats cpufreq_conservative rfcomm bnep binfmt_misc vboxdrv(O) synaptics_i2c firewire_sbp2 loop fuse parport_pc ppdev lp parport btusb gspca_m5602 gspca_main videodev bluetooth joydev media hid_generic usbhid hid pcspkr psmouse serio_raw evdev pcmcia snd_hda_codec_realtek r592 r852 sm_common nand nand_ecc i915 yenta_socket pcmcia_rsrc pcmcia_core lpc_ich mfd_core rng_core nand_ids memstick mtd drm_kms_helper drm i2c_algo_bit i2c_core acpi_cpufreq asus_laptop video ac battery snd_hda_intel snd_hda_codec snd_hwdep snd_pcm sparse_keymap snd_page_alloc rfkill processor button snd_seq snd_seq_device snd_timer input_polldev snd soundcore ext4 crc16 mbcache jbd2 sd_mod sg sr_mod crc_t10dif cdrom crct10dif_common ata_generic firewire_ohci sdhci_pci sdhci ata_piix 8139too firewire_core crc_itu_t 8139cp mii mmc_core libata scsi_mod thermal ehci_pci fan thermal_sys uhci_hcd ehci_hcd usbcore usb_common
[ 4247.778556] CPU: 0 PID: 81 Comm: khubd Tainted: G        W  O 3.13-1-686-pae #1 Debian 3.13.5-1
[ 4247.778563] Hardware name: ASUSTeK Computer Inc.         W5A       /W5A       , BIOS 0209                                11/17/2005
[ 4247.778569]  00000009 c140b038 00000000 c104d41e c14d7898 00000000 00000051 f8dbac14
[ 4247.778586]  000003c1 f8d7e95f f8d7e95f d9f36c00 e36d4920 d9f36c08 e36d5800 c104d4db
[ 4247.778603]  00000009 00000000 f8d7e95f d9f36000 c15a97dc e36d5800 e36d4800 c1657480
[ 4247.778620] Call Trace:
[ 4247.778631]  [<c140b038>] ? dump_stack+0x3e/0x4e
[ 4247.778641]  [<c104d41e>] ? warn_slowpath_common+0x7e/0xa0
[ 4247.778665]  [<f8d7e95f>] ? cfg80211_netdev_notifier_call+0x2bf/0x5a0 [cfg80211]
[ 4247.778687]  [<f8d7e95f>] ? cfg80211_netdev_notifier_call+0x2bf/0x5a0 [cfg80211]
[ 4247.778698]  [<c104d4db>] ? warn_slowpath_null+0x1b/0x20
[ 4247.778720]  [<f8d7e95f>] ? cfg80211_netdev_notifier_call+0x2bf/0x5a0 [cfg80211]
[ 4247.778732]  [<c133380d>] ? skb_dequeue+0x3d/0x50
[ 4247.778743]  [<c1347c80>] ? pneigh_queue_purge+0x20/0x30
[ 4247.778755]  [<c13f129a>] ? ip6mr_device_event+0x8a/0xb0
[ 4247.778767]  [<c13fbe5c>] ? packet_notifier+0x5c/0x170
[ 4247.778778]  [<c1412d16>] ? notifier_call_chain+0x46/0x60
[ 4247.778790]  [<c106ce67>] ? raw_notifier_call_chain+0x17/0x20
[ 4247.778802]  [<c133df0f>] ? rollback_registered_many+0x12f/0x220
[ 4247.778820]  [<c133e01a>] ? rollback_registered+0x1a/0x30
[ 4247.778831]  [<c133e45f>] ? unregister_netdevice_queue+0x3f/0xa0
[ 4247.778852]  [<c133e4d1>] ? unregister_netdev+0x11/0x20
[ 4247.778924]  [<f9050ca0>] ? rtw_usb_if1_deinit+0x36/0x7f [8812au]
[ 4247.778997]  [<f9050df0>] ? rtw_dev_remove+0x47/0x51 [8812au]
[ 4247.779031]  [<f826b303>] ? usb_unbind_interface+0x43/0x180 [usbcore]
[ 4247.779048]  [<c12f1649>] ? __device_release_driver+0x59/0xb0
[ 4247.779059]  [<c12f16b5>] ? device_release_driver+0x15/0x20
[ 4247.779070]  [<c12f114a>] ? bus_remove_device+0xaa/0xe0
[ 4247.779081]  [<c12eeaf3>] ? device_del+0xe3/0x170
[ 4247.779112]  [<f8269381>] ? usb_disable_device+0x81/0x1c0 [usbcore]
[ 4247.779142]  [<f8260ba0>] ? usb_disconnect+0x80/0x150 [usbcore]
[ 4247.779176]  [<f8263353>] ? hub_thread+0x483/0x10d0 [usbcore]
[ 4247.779195]  [<c1081320>] ? prepare_to_wait_event+0xc0/0xc0
[ 4247.779224]  [<f8262ed0>] ? usb_reset_device+0x140/0x140 [usbcore]
[ 4247.779235]  [<c1068c6e>] ? kthread+0x9e/0xc0
[ 4247.779247]  [<c14161f7>] ? ret_from_kernel_thread+0x1b/0x28
[ 4247.779258]  [<c1068bd0>] ? kthread_create_on_node+0x110/0x110
[ 4247.779266] ---[ end trace ff41ae88874c3db5 ]---

Same happens with 3.14-rc6.
Let me know if I can help solving this issue.

Regards

nb

**Comment by harshavardhana** [comment]
Fixed in repo. closing
