### ISSUE TITLE
Compilation failure with DBG=1

### ISSUE THREAD

**Issue by harshavardhana** [abperiasamy/rtl8812AU_8821AU_linux#8]
$ make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/3.5.0-47-generic/build M=/home/harsha/repos/rtl8812AU_8821AU_linux  modules
make[1]: Entering directory `/usr/src/linux-headers-3.5.0-47-generic'
  CC [M]  /home/harsha/repos/rtl8812AU_8821AU_linux/core/rtw_cmd.o
  CC [M]  /home/harsha/repos/rtl8812AU_8821AU_linux/core/rtw_security.o
  CC [M]  /home/harsha/repos/rtl8812AU_8821AU_linux/core/rtw_debug.o
  CC [M]  /home/harsha/repos/rtl8812AU_8821AU_linux/core/rtw_io.o
  CC [M]  /home/harsha/repos/rtl8812AU_8821AU_linux/core/rtw_ioctl_query.o
  CC [M]  /home/harsha/repos/rtl8812AU_8821AU_linux/core/rtw_ioctl_set.o
  CC [M]  /home/harsha/repos/rtl8812AU_8821AU_linux/core/rtw_ieee80211.o
  CC [M]  /home/harsha/repos/rtl8812AU_8821AU_linux/core/rtw_mlme.o
  CC [M]  /home/harsha/repos/rtl8812AU_8821AU_linux/core/rtw_mlme_ext.o
  CC [M]  /home/harsha/repos/rtl8812AU_8821AU_linux/core/rtw_wlan_util.o
  CC [M]  /home/harsha/repos/rtl8812AU_8821AU_linux/core/rtw_vht.o
  CC [M]  /home/harsha/repos/rtl8812AU_8821AU_linux/core/rtw_pwrctrl.o
  CC [M]  /home/harsha/repos/rtl8812AU_8821AU_linux/core/rtw_rf.o
  CC [M]  /home/harsha/repos/rtl8812AU_8821AU_linux/core/rtw_recv.o
  CC [M]  /home/harsha/repos/rtl8812AU_8821AU_linux/core/rtw_sta_mgt.o
  CC [M]  /home/harsha/repos/rtl8812AU_8821AU_linux/core/rtw_ap.o
  CC [M]  /home/harsha/repos/rtl8812AU_8821AU_linux/core/rtw_xmit.o
  CC [M]  /home/harsha/repos/rtl8812AU_8821AU_linux/core/rtw_p2p.o
  CC [M]  /home/harsha/repos/rtl8812AU_8821AU_linux/core/rtw_tdls.o
  CC [M]  /home/harsha/repos/rtl8812AU_8821AU_linux/core/rtw_br_ext.o
  CC [M]  /home/harsha/repos/rtl8812AU_8821AU_linux/core/rtw_iol.o
  CC [M]  /home/harsha/repos/rtl8812AU_8821AU_linux/core/rtw_sreset.o
  CC [M]  /home/harsha/repos/rtl8812AU_8821AU_linux/core/efuse/rtw_efuse.o
  CC [M]  /home/harsha/repos/rtl8812AU_8821AU_linux/os_dep/osdep_service.o
  CC [M]  /home/harsha/repos/rtl8812AU_8821AU_linux/os_dep/linux/os_intfs.o
/home/harsha/repos/rtl8812AU_8821AU_linux/os_dep/linux/os_intfs.c: In function ‘rtw_proc_init_one’:
/home/harsha/repos/rtl8812AU_8821AU_linux/os_dep/linux/os_intfs.c:1301:22: error: ‘proc_set_btcoex_dbg’ undeclared (first use in this function)
/home/harsha/repos/rtl8812AU_8821AU_linux/os_dep/linux/os_intfs.c:1301:22: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [/home/harsha/repos/rtl8812AU_8821AU_linux/os_dep/linux/os_intfs.o] Error 1
make[1]: *** [_module_/home/harsha/repos/rtl8812AU_8821AU_linux] Error 2
make[1]: Leaving directory `/usr/src/linux-headers-3.5.0-47-generic'
make: *** [modules] Error 2

**Comment by bits3rpent** [comment]
I will work on this on my repo, this repo does not seem to be that active anymore.

**Comment by bits3rpent** [comment]
Fixed in my repo. https://github.com/bits3rpent/rtl8812AU_8821AU_linux

**Comment by harshavardhana** [comment]
Fixed in latest merge.
